apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    tier: frontend

spec:
# Service type is nodeport (duh!)
  type: NodePort

# Now set the ports
  ports:
# Set the port of the service's internal ClusterIP
  - port: 8080

# Targeted port
    targetPort: 8080
    nodePort: 31000

# Labels to "tie" the service to the deployment
  selector:
    tier: frontend

