apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    run: gowebapp
    tier: frontend

spec:
  replicas: 1
  selector:
    matchLabels:
      run: gowebapp
      tier: frontend

  template:
      metadata:
        labels:
          run: gowebapp
          tier: frontend
      spec:
        containers:
        - name: gowebapp
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: mypassword
          image: wweissborn/homework:frontend-1.3
          ports:
          - containerPort: 80

